export const FETCH_CHARACTERS_START = 'FETCH_CHARACTERS_START';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAIL = 'FETCH_CHARACTERS_FAIL';

export const FETCH_ONE_CHAR_SUCCESS = 'FETCH_ONE_CHAR_SUCCESS';

export const REQUEST_MOVIES_START = 'REQUEST_MOVIES_START';
export const REQUEST_MOVIES_SUCCESS = 'REQUEST_MOVIES_SUCCESS';
export const REQUEST_MOVIES_FAILED = 'REQUEST_MOVIES_FAILED';