export const FETCH_CHARACTERS_START = 'FETCH_CHARACTERS_START';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAIL = 'FETCH_CHARACTERS_FAIL';

export const REQUEST_ONE_CHAR_START = 'REQUEST_ONE_CHAR_START';
export const REQUEST_ONE_CHAR_SUCCESS = 'REQUEST_ONE_CHAR_SUCCESS';
export const REQUEST_ONE_CHAR_FAILED = 'REQUEST_ONE_CHAR_FAILED';

export const REQUEST_RELATED_MOVIES_START = 'REQUEST_RELATED_MOVIES_START';
export const REQUEST_RELATED_MOVIES_SUCCESS = 'REQUEST_RELATED_MOVIES_SUCCESS';
export const REQUEST_RELATED_MOVIES_FAILED = 'REQUEST_RELATED_MOVIES_FAILED';

export const REQUEST_RELATED_VEHICULES_START = 'REQUEST_RELATED_VEHICULES_START';
export const REQUEST_RELATED_VEHICULES_SUCCESS = 'REQUEST_RELATED_VEHICULES_SUCCESS';
export const REQUEST_RELATED_VEHICULES_FAILED = 'REQUEST_RELATED_VEHICULES_FAILED';

export const REQUEST_RELATED_STARSHIPS_START = 'REQUEST_RELATED_STARSHIPS_START';
export const REQUEST_RELATED_STARSHIPS_SUCCESS = 'REQUEST_RELATED_STARSHIPS_SUCCESS';
export const REQUEST_RELATED_STARSHIPS_FAILED = 'REQUEST_RELATED_STARSHIPS_FAILED';

export const PLANETS_START = 'PLANETS_START';
export const PLANETS_SUCCESS = 'PLANETS_SUCCESS';
export const PLANETS_FAILED = 'PLANETS_FAILED';
export const ALL_PLANETS_START = 'ALL_PLANETS_START';
export const ALL_PLANETS_SUCCESS = 'ALL_PLANETS_SUCCESS';
export const ALL_PLANETS_FAILED = 'ALL_PLANETS_FAILED';

export const FILMS_START = 'FILMS_START';
export const FILMS_SUCCESS = 'FILMS_SUCCESS';
export const FILMS_FAILED = 'FILMS_FAILED';
export const ALL_FILMS_START = 'ALL_FILMS_START';
export const ALL_FILMS_SUCCESS = 'ALL_FILMS_SUCCESS';
export const ALL_FILMS_FAILED = 'ALL_FILMS_FAILED';

export const REQUEST_EACH_FROM_LIST_START = 'REQUEST_EACH_FROM_LIST_START';
export const REQUEST_EACH_FROM_LIST_SUCCESS = 'REQUEST_EACH_FROM_LIST_SUCCESS';
export const REQUEST_EACH_FROM_LIST_FAILED = 'REQUEST_EACH_FROM_LIST_FAILED';