export const FETCH_CHARACTERS_START = 'FETCH_CHARACTERS_START';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAIL = 'FETCH_CHARACTERS_FAIL';

export const REQUEST_ONE_CHAR_START = 'REQUEST_ONE_CHAR_START';
export const REQUEST_ONE_CHAR_SUCCESS = 'REQUEST_ONE_CHAR_SUCCESS';
export const REQUEST_ONE_CHAR_FAILED = 'REQUEST_ONE_CHAR_FAILED';

export const REQUEST_RELATED_ITEMS_START = 'REQUEST_RELATED_ITEMS_START';
export const REQUEST_RELATED_ITEMS_SUCCESS = 'REQUEST_RELATED_ITEMS_SUCCESS';
export const REQUEST_RELATED_ITEMS_FAILED = 'REQUEST_RELATED_ITEMS_FAILED';